=== projecthdata/lab-content-profile/schemas/root.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Copyright 2009 The MITRE Corporation 
  
  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. 
  You may obtain a copy of the License at 
  
  http://www.apache.org/licenses/LICENSE-2.0 
  
  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific 
  language governing permissions and limitations under the License. 
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://projecthdata.org/hdata/schemas/2009/06/core" xmlns:core="http://projecthdata.org/hdata/schemas/2009/06/core">
  <xs:element name="root">
    <xs:complexType>
      <xs:all>
        <xs:element ref="core:documentId"/>
        <xs:element ref="core:version"/>
        <xs:element ref="core:created"/>
        <xs:element ref="core:lastModified"/>
        <xs:element ref="core:extensions"/>
        <xs:element ref="core:sections"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="documentId" type="xs:string"/>
  <xs:element name="version" type="xs:string"/>
  <xs:element name="created" type="xs:date"/>
  <xs:element name="lastModified" type="xs:date"/>
  <xs:element name="extensions">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="core:extension"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="extension">
    <xs:complexType mixed="true">
      <xs:attribute name="requirement" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="mandatory"/>
            <xs:enumeration value="optional"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="contentType" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sections">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="core:section"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
 
  <xs:element name="section">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="core:section"/>
      </xs:sequence>
      <xs:attribute name="path" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="typeId" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== projecthdata/lab-content-profile/hdata-examples/simple/root.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://projecthdata.org/hdata/schemas/2009/06/core ../../../hData/schemas/2009/06/root.xsd"
 xmlns="http://projecthdata.org/hdata/schemas/2009/06/core">
    <documentId>documentid0</documentId>
    <version>0.8</version>
    <created>2010-02-09</created>
    <lastModified>2010-02-09</lastModified>
    <extensions>
        <extension requirement="mandatory" contentType="text/xml">http://projecthdata.org/hdata/schemas/2009/06/insurance_provider</extension>
        <extension requirement="mandatory" contentType="text/xml">http://projecthdata.org/hdata/schemas/2009/06/patient_information</extension>
        <extension requirement="mandatory" contentType="text/xml">http://projecthdata.org/hdata/schemas/2009/06/result</extension>
        <extension requirement="mandatory" contentType="text/xml">http://projecthdata.org/hdata/schemas/2010/01/order</extension>
    </extensions>
    <sections>      
      <section typeId="http://projecthdata.org/hdata/schemas/2009/06/patient_information" path="patient_information" name="Patient Information"/>
      <section typeId="http://projecthdata.org/hdata/schemas/2009/06/result" path="results" name="Results"/>
      <section typeId="http://projecthdata.org/hdata/schemas/2009/06/insurance_provider" path="insurance_providers" name="Insurance Provider"/>
      <section typeId="http://projecthdata.org/hdata/schemas/2010/01/order" path="orders" name="Orders"/>
    </sections>
</root>
